# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AirborneNumericalsvdTDk.ui'
##
## Created by: Qt User Interface Compiler version 5.15.8
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *  # type: ignore
from PySide2.QtGui import *  # type: ignore
from PySide2.QtWidgets import *  # type: ignore


class airborneNumericalWindow(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1610, 963)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QSize(1610, 963))
        Form.setMaximumSize(QSize(1610, 963))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(u"background-color : white")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 1611, 41))
        font = QFont()
        font.setFamily(u"DejaVu Sans")
        font.setPointSize(18)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color : 	rgb( 0, 0, 60)")
        self.label.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 50, 491, 751))
        self.groupBox.setStyleSheet(u"background-color : rgb( 0, 0, 110)")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 10, 91, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(True)
        font1.setWeight(75)
        self.label_2.setFont(font1)
        self.label_2.setWordWrap(True)
        self.introduction_button = QPushButton(self.groupBox)
        self.introduction_button.setObjectName(u"introduction_button")
        self.introduction_button.setGeometry(QRect(30, 50, 30, 30))
        font2 = QFont()
        font2.setKerning(True)
        self.introduction_button.setFont(font2)
        self.introduction_button.setAutoFillBackground(False)
        self.introduction_button.setStyleSheet(u"background-color : pink")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 40, 105, 41))
        font3 = QFont()
        font3.setPointSize(12)
        self.label_3.setFont(font3)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(70, 80, 231, 41))
        self.label_4.setFont(font3)
        self.speedandfuel_button = QPushButton(self.groupBox)
        self.speedandfuel_button.setObjectName(u"speedandfuel_button")
        self.speedandfuel_button.setGeometry(QRect(30, 90, 30, 30))
        self.speedandfuel_button.setAutoFillBackground(False)
        self.speedandfuel_button.setStyleSheet(u"background-color : chocolate")
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(70, 120, 231, 41))
        self.label_5.setFont(font3)
        self.speedandparcel_button = QPushButton(self.groupBox)
        self.speedandparcel_button.setObjectName(u"speedandparcel_button")
        self.speedandparcel_button.setGeometry(QRect(30, 130, 30, 30))
        self.speedandparcel_button.setAutoFillBackground(False)
        self.speedandparcel_button.setStyleSheet(u"background-color : cyan")
        self.menudisplaywidget = QWidget(self.groupBox)
        self.menudisplaywidget.setObjectName(u"menudisplaywidget")
        self.menudisplaywidget.setGeometry(QRect(0, 180, 461, 561))
        self.introductiontextbrowser = QTextBrowser(self.menudisplaywidget)
        self.introductiontextbrowser.setObjectName(u"introductiontextbrowser")
        self.introductiontextbrowser.setGeometry(QRect(30, 120, 421, 381))
        font4 = QFont()
        font4.setPointSize(10)
        self.introductiontextbrowser.setFont(font4)
        self.introductiontextbrowser.setAutoFillBackground(True)
        self.introductiontextbrowser.setStyleSheet(u"background-color : darkgreen")
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(500, 50, 1111, 471))
        self.groupBox_2.setStyleSheet(u"background-color : rgb( 0, 0, 110)")
        self.gridmap = QFrame(self.groupBox_2)
        self.gridmap.setObjectName(u"gridmap")
        self.gridmap.setGeometry(QRect(80, 40, 950, 391))
        self.gridmap.setStyleSheet(u"background-color : white")
        self.gridmap.setFrameShape(QFrame.StyledPanel)
        self.gridmap.setFrameShadow(QFrame.Raised)
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(500, 530, 1111, 201))
        self.groupBox_3.setStyleSheet(u"background-color : rgb( 0, 0, 110)")
        self.groupBox_7 = QGroupBox(self.groupBox_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(350, 40, 411, 121))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy1)
        self.groupBox_7.setStyleSheet(u"background-color : black")
        self.label_6 = QLabel(self.groupBox_7)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 20, 91, 31))
        font5 = QFont()
        font5.setPointSize(16)
        font5.setBold(True)
        font5.setWeight(75)
        self.label_6.setFont(font5)
        self.label_7 = QLabel(self.groupBox_7)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 70, 61, 21))
        self.label_7.setFont(font5)
        self.mission_label = QLabel(self.groupBox_7)
        self.mission_label.setObjectName(u"mission_label")
        self.mission_label.setGeometry(QRect(120, 20, 281, 31))
        font6 = QFont()
        font6.setPointSize(16)
        font6.setBold(False)
        font6.setWeight(50)
        self.mission_label.setFont(font6)
        self.task_label = QLabel(self.groupBox_7)
        self.task_label.setObjectName(u"task_label")
        self.task_label.setGeometry(QRect(90, 70, 281, 21))
        self.task_label.setFont(font6)
        self.groupBox_4 = QGroupBox(Form)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 810, 491, 111))
        self.groupBox_4.setStyleSheet(u"background-color : rgb( 0, 0, 110)")
        self.speedformula_textbrowser = QTextBrowser(self.groupBox_4)
        self.speedformula_textbrowser.setObjectName(u"speedformula_textbrowser")
        self.speedformula_textbrowser.setGeometry(QRect(80, 10, 321, 91))
        self.speedformula_textbrowser.setFont(font4)
        self.speedformula_textbrowser.setLayoutDirection(Qt.LeftToRight)
        self.speedformula_textbrowser.setAutoFillBackground(True)
        self.speedformula_textbrowser.setStyleSheet(u"background-color : darkgreen")
        self.speedformula_textbrowser.setTabStopWidth(81)
        self.speedformula_textbrowser.setCursorWidth(0)
        self.groupBox_5 = QGroupBox(Form)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 930, 1651, 41))
        self.groupBox_5.setStyleSheet(u"background-color : black")
        self.timeleft_label = QLabel(self.groupBox_5)
        self.timeleft_label.setObjectName(u"timeleft_label")
        self.timeleft_label.setGeometry(QRect(1470, -10, 131, 51))
        self.timeleft_label.setFont(font3)
        self.question_label = QLabel(self.groupBox_5)
        self.question_label.setObjectName(u"question_label")
        self.question_label.setGeometry(QRect(30, -10, 131, 51))
        self.question_label.setFont(font3)
        self.groupBox_6 = QGroupBox(Form)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(500, 740, 1111, 181))
        self.groupBox_6.setStyleSheet(u"background-color : rgb( 0, 0, 110)")
        self.ETAtableview = QTableView(self.groupBox_6)
        self.ETAtableview.setObjectName(u"ETAtableview")
        self.ETAtableview.setGeometry(QRect(140, 20, 831, 141))
        self.whiteframe = QFrame(Form)
        self.whiteframe.setObjectName(u"whiteframe")
        self.whiteframe.setGeometry(QRect(-1, 0, 1611, 971))
        self.whiteframe.setAutoFillBackground(False)
        self.whiteframe.setFrameShape(QFrame.StyledPanel)
        self.whiteframe.setFrameShadow(QFrame.Raised)
        self.whiteframe.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Airborne Numerical Test", None))
        self.groupBox.setTitle("")
        self.label_2.setText(QCoreApplication.translate("Form", u"Menu", None))
        self.introduction_button.setText("")
        self.label_3.setText(QCoreApplication.translate("Form", u"Introduction", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Speed and Fuel Consumption", None))
        self.speedandfuel_button.setText("")
        self.label_5.setText(QCoreApplication.translate("Form", u"Speed and Parcel Weight", None))
        self.speedandparcel_button.setText("")
        self.introductiontextbrowser.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">You are the operator of a large Remote Controlled Aerial Vehicle.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The Aerial Vehicle operates as part of a high-tech mail delivery service.</span></p>\n"
"<p style=\"-qt-paragraph-type:emp"
                        "ty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Always assume refuelling and deliveries and collections take no time.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Answer in whole numbers only. Always round up if the answer is 0.5 or greater and round down if the answer is 0.49 or less.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>"
                        "\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Work as quickly and as accurately as possible.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">However you will be given marks for estimated answers.</span></p></body></html>", None))
        self.groupBox_2.setTitle("")
        self.groupBox_3.setTitle("")
        self.groupBox_7.setTitle("")
        self.label_6.setText(QCoreApplication.translate("Form", u"Mission:", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Task:", None))
        self.mission_label.setText(QCoreApplication.translate("Form", u"Deliver parcel to Whisky.", None))
        self.task_label.setText(QCoreApplication.translate("Form", u"Calculate arrival time.", None))
        self.groupBox_4.setTitle("")
        self.speedformula_textbrowser.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Speed = Distance / Time</span></p></body></html>", None))
        self.groupBox_5.setTitle("")
        self.timeleft_label.setText(QCoreApplication.translate("Form", u"Time Left: 00:59", None))
        self.question_label.setText(QCoreApplication.translate("Form", u"Question 1", None))
        self.groupBox_6.setTitle("")
    # retranslateUi

